/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import Utilidades.LimitedTextField;
import controle.ControleConsulta;
import visao.dialogs.DialogBuscaConsulta;
import controle.ControleExame;
import controle.ControleMedicamento;
import controle.ControlePreConsulta;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Consulta;
import modelo.ItemDeExame;
import modelo.ItemDeReceita;
import modelo.Medico;
import static org.jdesktop.observablecollections.ObservableCollections.observableList;
import visao.dialogs.DialogBuscaExame;
import visao.dialogs.DialogBuscaMedicamento;

/**
 *
 * @author Bianca
 */
public class TelaConsulta extends javax.swing.JInternalFrame {

    private ControleExame controleExame;
    private ControleMedicamento controleMedicamento;
    private ControlePreConsulta controlePreConsulta;
    private Consulta conPaciente = null;
    private Medico med = null;
    private ControleConsulta controleConsulta;

    public TelaConsulta(Medico med) {
        this.med = med;
        controleExame = new ControleExame();
        controleMedicamento = new ControleMedicamento();
        controlePreConsulta = new ControlePreConsulta();
        controleConsulta = new ControleConsulta();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listaExames = observableList(new ArrayList<>());
        listaMedicamentos = observableList(new ArrayList<>());
        listaConsultas = observableList(new ArrayList<Consulta>());
        areaDeTrabalho = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDadosPre = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        salvar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        concFinais = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiag = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObserva = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaExames = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelaMedicamentos = new javax.swing.JTable();
        excluirMedicamentos = new javax.swing.JButton();
        excluirExames = new javax.swing.JButton();
        addExame = new javax.swing.JButton();
        addMedicamento = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        areaTextoConsultas = new javax.swing.JTextArea();
        botVisualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaConsultas = new javax.swing.JTable();
        fechar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtficha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        botSelecionar1 = new javax.swing.JButton();

        setClosable(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Agendar Retorno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtDadosPre.setEditable(false);
        txtDadosPre.setBackground(new java.awt.Color(240, 240, 240));
        txtDadosPre.setColumns(20);
        txtDadosPre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDadosPre.setRows(5);
        txtDadosPre.setBorder(null);
        jScrollPane1.setViewportView(txtDadosPre);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logomenor.png"))); // NOI18N

        salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salvarMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconesNovos/icons8-Save Close-40.png"))); // NOI18N

        javax.swing.GroupLayout salvarLayout = new javax.swing.GroupLayout(salvar);
        salvar.setLayout(salvarLayout);
        salvarLayout.setHorizontalGroup(
            salvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salvarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        salvarLayout.setVerticalGroup(
            salvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salvarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        concFinais.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Conclusões Finais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        txtDiag.setDocument(new LimitedTextField(500));
        txtDiag.setBackground(new java.awt.Color(240, 240, 240));
        txtDiag.setColumns(20);
        txtDiag.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDiag.setRows(5);
        txtDiag.setBorder(null);
        jScrollPane2.setViewportView(txtDiag);

        txtObserva.setDocument(new LimitedTextField(500));
        txtObserva.setBackground(new java.awt.Color(240, 240, 240));
        txtObserva.setColumns(20);
        txtObserva.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtObserva.setRows(5);
        txtObserva.setBorder(null);
        jScrollPane3.setViewportView(txtObserva);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Diagnóstico");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Observações e Encaminhamentos");

        javax.swing.GroupLayout concFinaisLayout = new javax.swing.GroupLayout(concFinais);
        concFinais.setLayout(concFinaisLayout);
        concFinaisLayout.setHorizontalGroup(
            concFinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(concFinaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(concFinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(concFinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(concFinaisLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)))
        );
        concFinaisLayout.setVerticalGroup(
            concFinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(concFinaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(concFinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(concFinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Dados da Pré-Consulta");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Extras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Medicamentos Prescritos");

        tabelaExames.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabelaExames.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaExames, tabelaExames);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${exame.descricao}"));
        columnBinding.setColumnName("Exame");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane4.setViewportView(tabelaExames);
        if (tabelaExames.getColumnModel().getColumnCount() > 0) {
            tabelaExames.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Exames");

        tabelaMedicamentos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabelaMedicamentos.getTableHeader().setReorderingAllowed(false);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaMedicamentos, tabelaMedicamentos);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${medicamento.descricao}"));
        columnBinding.setColumnName("Medicamento");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dosagem}"));
        columnBinding.setColumnName("Dosagem");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${periodicidade}"));
        columnBinding.setColumnName("Periodicidade");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane6.setViewportView(tabelaMedicamentos);
        if (tabelaMedicamentos.getColumnModel().getColumnCount() > 0) {
            tabelaMedicamentos.getColumnModel().getColumn(0).setResizable(false);
            tabelaMedicamentos.getColumnModel().getColumn(1).setResizable(false);
            tabelaMedicamentos.getColumnModel().getColumn(2).setResizable(false);
        }

        excluirMedicamentos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        excluirMedicamentos.setText("Excluir");
        excluirMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirMedicamentosActionPerformed(evt);
            }
        });

        excluirExames.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        excluirExames.setText("Excluir");
        excluirExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirExamesActionPerformed(evt);
            }
        });

        addExame.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addExame.setText("Prescrever Exame");
        addExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExameActionPerformed(evt);
            }
        });

        addMedicamento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addMedicamento.setText("Receitar Medicamentos");
        addMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedicamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirMedicamentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(148, 148, 148)
                                .addComponent(excluirExames)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addExame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(excluirMedicamentos)
                    .addComponent(addMedicamento))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(excluirExames)
                    .addComponent(addExame))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        areaTextoConsultas.setEditable(false);
        areaTextoConsultas.setBackground(new java.awt.Color(240, 240, 240));
        areaTextoConsultas.setColumns(20);
        areaTextoConsultas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        areaTextoConsultas.setRows(5);
        areaTextoConsultas.setBorder(null);
        jScrollPane7.setViewportView(areaTextoConsultas);

        botVisualizar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        botVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/olho.png"))); // NOI18N
        botVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVisualizarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Consultas Anteriores");

        tabelaConsultas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabelaConsultas.getTableHeader().setReorderingAllowed(false);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaConsultas, tabelaConsultas);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${preconsulta.medico.nome}"));
        columnBinding.setColumnName("Médico");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataConsul}"));
        columnBinding.setColumnName("Data Consul");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${situacao}"));
        columnBinding.setColumnName("Situacao");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane5.setViewportView(tabelaConsultas);
        if (tabelaConsultas.getColumnModel().getColumnCount() > 0) {
            tabelaConsultas.getColumnModel().getColumn(0).setResizable(false);
            tabelaConsultas.getColumnModel().getColumn(1).setResizable(false);
            tabelaConsultas.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(botVisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fecharMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fecharMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconesNovos/icons8-Cancel-40.png"))); // NOI18N

        javax.swing.GroupLayout fecharLayout = new javax.swing.GroupLayout(fechar);
        fechar.setLayout(fecharLayout);
        fecharLayout.setHorizontalGroup(
            fecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fecharLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        fecharLayout.setVerticalGroup(
            fecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fecharLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        txtficha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtficha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estetoscopio.png"))); // NOI18N
        txtficha.setText("Consulta");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Paciente");

        txtPaciente.setEditable(false);
        txtPaciente.setBackground(new java.awt.Color(240, 240, 240));
        txtPaciente.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtPaciente.setBorder(null);

        botSelecionar1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        botSelecionar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/searchmenor.png"))); // NOI18N
        botSelecionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSelecionar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1562, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(txtficha, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                                .addComponent(txtPaciente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botSelecionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(concFinais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(90, 90, 90)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtficha)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel1)
                                            .addGap(8, 8, 8)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(botSelecionar1))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(concFinais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 6, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );

        areaDeTrabalho.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout areaDeTrabalhoLayout = new javax.swing.GroupLayout(areaDeTrabalho);
        areaDeTrabalho.setLayout(areaDeTrabalhoLayout);
        areaDeTrabalhoLayout.setHorizontalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        areaDeTrabalhoLayout.setVerticalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(areaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVisualizarActionPerformed
        int posicao = tabelaConsultas.getSelectedRow();
        if (posicao != -1) {
            Consulta selected = listaConsultas.get(posicao);

            areaTextoConsultas.setText(selected.toString());
            if (selected.isSituacao()) {
                Color verdeEscuro = new Color(35, 142, 35);
                areaTextoConsultas.setForeground(verdeEscuro);
            } else {
                areaTextoConsultas.setForeground(Color.red);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma Pré-Consulta!");
        }
    }//GEN-LAST:event_botVisualizarActionPerformed

    private void addExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExameActionPerformed
        DialogBuscaExame tela;
        tela = new DialogBuscaExame(null, true);
        tela.setVisible(true);
        if (tela.getExameSelecionado() != null) {
            ItemDeExame item = new ItemDeExame();
            item.setExame(tela.getExameSelecionado());
            item.setConsulta(conPaciente);
            listaExames.add(item);
        }
    }//GEN-LAST:event_addExameActionPerformed

    private void addMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicamentoActionPerformed
        DialogBuscaMedicamento tela;
        tela = new DialogBuscaMedicamento(null, true);
        tela.setVisible(true);
        if (tela.getMedicamSelecionado() != null) {
            ItemDeReceita item;
            item = new ItemDeReceita();
            item.setMedicamento(tela.getMedicamSelecionado());
            item.setConsulta(conPaciente);
            item.setDosagem(tela.getDosagem());
            item.setPeriodicidade(tela.getPeriodicidade());
            listaMedicamentos.add(item);
        }
    }//GEN-LAST:event_addMedicamentoActionPerformed

    private void botSelecionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSelecionar1ActionPerformed
        DialogBuscaConsulta tela;
        tela = new DialogBuscaConsulta(null, true);
        tela.setVisible(true);
        if (tela.getSelecionada() != null) {
            conPaciente = tela.getSelecionada();
            txtPaciente.setText(conPaciente.getPreconsulta().getFichaatend().getPaciente().getNome());
            txtDadosPre.setText(conPaciente.toString());
            listaConsultas.clear();
            listaConsultas.addAll(controleConsulta.listaConsultasPciente(conPaciente.getPreconsulta().getFichaatend().getPaciente()));
        }
    }//GEN-LAST:event_botSelecionar1ActionPerformed

    private void excluirMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirMedicamentosActionPerformed
        int posicao = tabelaMedicamentos.getSelectedRow();
        if (posicao != -1) {
            listaMedicamentos.remove(posicao);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um medicamento!");
        }
    }//GEN-LAST:event_excluirMedicamentosActionPerformed

    private void excluirExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirExamesActionPerformed
        int posicao = tabelaExames.getSelectedRow();
        if (posicao != -1) {
            listaExames.remove(posicao);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um exame!");
        }
    }//GEN-LAST:event_excluirExamesActionPerformed

    private void salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarMouseClicked
        if (!txtObserva.getText().isEmpty() && !txtDiag.getText().isEmpty() && conPaciente != null) {
            
            
            conPaciente.setDataConsul(new Date());
            conPaciente.setDiagnostico(txtDiag.getText());
            
            conPaciente.setObservacoes(txtObserva.getText());
            conPaciente.setPreconsulta(conPaciente.getPreconsulta());
            conPaciente.setSituacao(true);
            
            
            
            conPaciente.setItensExame(listaExames);
            conPaciente.setItensOrc(listaMedicamentos);
            controleConsulta.alterar(conPaciente);
            
            JOptionPane.showMessageDialog(this, "Concluido!");
            txtDiag.setText("");
            txtObserva.setText("");
            listaExames.clear();
            listaConsultas.clear();
            listaMedicamentos.clear();
            conPaciente = null;
            txtPaciente.setText("");
            txtDadosPre.setText("");
            areaTextoConsultas.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Preencha corretamente as lacunas!");
        }
    }//GEN-LAST:event_salvarMouseClicked

    private void salvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarMouseEntered
        Color cinza = new Color(153, 153, 153);
        salvar.setBackground(cinza);
    }//GEN-LAST:event_salvarMouseEntered

    private void salvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarMouseExited
        Color cinza = new Color(240, 240, 240);
        salvar.setBackground(cinza);
    }//GEN-LAST:event_salvarMouseExited

    private void fecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharMouseEntered
        Color cinza = new Color(153, 153, 153);
        fechar.setBackground(cinza);
    }//GEN-LAST:event_fecharMouseEntered

    private void fecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharMouseExited
        Color cinza = new Color(240, 240, 240);
        fechar.setBackground(cinza);
    }//GEN-LAST:event_fecharMouseExited

    private void fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharMouseClicked
        txtDiag.setText("");
        txtObserva.setText("");
        listaExames.clear();
        listaConsultas.clear();
        listaMedicamentos.clear();
        conPaciente = null;
        txtPaciente.setText("");
        txtDadosPre.setText("");
    }//GEN-LAST:event_fecharMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (conPaciente!=null){
        TelaRetorno tela = new TelaRetorno(conPaciente.getPreconsulta().getFichaatend().getPaciente());
         areaDeTrabalho.add(tela);
        tela.setVisible(true);
        
        }else{
              JOptionPane.showMessageDialog(this, "Não há um paciente!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExame;
    private javax.swing.JButton addMedicamento;
    private javax.swing.JDesktopPane areaDeTrabalho;
    private javax.swing.JTextArea areaTextoConsultas;
    private javax.swing.JButton botSelecionar1;
    private javax.swing.JButton botVisualizar;
    private javax.swing.JPanel concFinais;
    private javax.swing.JButton excluirExames;
    private javax.swing.JButton excluirMedicamentos;
    private javax.swing.JPanel fechar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private java.util.List<Consulta> listaConsultas;
    private java.util.List<ItemDeExame> listaExames;
    private java.util.List<ItemDeReceita> listaMedicamentos;
    private javax.swing.JPanel salvar;
    private javax.swing.JTable tabelaConsultas;
    private javax.swing.JTable tabelaExames;
    private javax.swing.JTable tabelaMedicamentos;
    private javax.swing.JTextArea txtDadosPre;
    private javax.swing.JTextArea txtDiag;
    private javax.swing.JTextArea txtObserva;
    private javax.swing.JTextField txtPaciente;
    private javax.swing.JLabel txtficha;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
