package visao.inicio;

import Utilidades.AtualizadorHorario;
import controle.ControleConsulta;
import controle.ControleFuncionario;
import controle.ControleMedico;
import controle.ControlePreConsulta;
import java.awt.Color;
import java.awt.Font;
import static java.awt.image.ImageObserver.WIDTH;
import java.beans.PropertyVetoException;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import modelo.Consulta;
import modelo.FichaAtendimento;
import modelo.Medico;
import modelo.Pessoa;
import modelo.PreConsulta;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import static org.jdesktop.observablecollections.ObservableCollections.observableList;
import visao.PacienteProntuario;
//import visao.PacienteProntuario;
import visao.crud.ManterExame;
import visao.crud.ManterMedicamento;
import visao.TelaConsulta;
import visao.TelaEditarPerfilMedico;
import visao.TelaRetorno;
import visao.TodasConsultas;
import visao.TodasConsultasDataRelatorio;
import visao.TodasPreConsultas;

/**
 *
 * @author Aluno
 */
public class InicioMedico extends javax.swing.JFrame {

    private Medico medic;

    private ControlePreConsulta controlePrec;
    private ControleMedico controleMed;
    private ControleFuncionario controleFuncionario;

    public InicioMedico() {
        controlePrec = new ControlePreConsulta();

        controleMed = new ControleMedico();

        controleFuncionario = new ControleFuncionario();
        initComponents();

        //this.setExtendedState(MAXIMIZED_HORIZ);
        AtualizadorHorario ah = new AtualizadorHorario(txttime, txtData);
        ah.mostrarData(true);
        Thread thHora = ah;
        thHora.start();
        medicamentos.setFont(new Font("Tahoma", WIDTH, 16));
        consultas.setFont(new Font("Tahoma", WIDTH, 16));
        pesquisas.setFont(new Font("Tahoma", WIDTH, 16));
        usuario.setFont(new Font("Tahoma", WIDTH, 16));
        exames.setFont(new Font("Tahoma", WIDTH, 16));
        txttime.setFont(new Font("Tahoma", WIDTH, 16));
        txtData.setFont(new Font("Tahoma", WIDTH, 16));
        relat.setFont(new Font("Tahoma", WIDTH, 16));
        if (ControleMedico.getLogado() != null) {
            medic = ControleMedico.getLogado();
            usuario.setText(medic.getNome());
        }
        for (Medico m : listaMedicos) {
            if (controlePrec.listaConsultasDataMed(new Date(), m) != null) {
                int i = controlePrec.listaConsultasDataMed(new Date(), m).size();
                tabelaMediDispon.setValueAt(Integer.toString(m.getMaxatendi() - i), listaMedicos.indexOf(m), 2);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listaMedicos = observableList(controleMed.medicosDisponiveisTudo());
        listaAgendadas = observableList(controlePrec.pesquisaPrecData(new Date())) ;
        areaDeTrabalho = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaMediDispon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        painelatt3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAgendadas = new javax.swing.JTable();
        painelatt2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPesquisaData = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        medicamentos = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        exames = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        consultas = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        pesquisas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        relat = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        usuario = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        txtData = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        txttime = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabelaMediDispon.setBackground(new java.awt.Color(240, 240, 240));
        tabelaMediDispon.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabelaMediDispon.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaMedicos, tabelaMediDispon);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${especialidade}"));
        columnBinding.setColumnName("Especialidade");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${maxatendi}"));
        columnBinding.setColumnName("Maxatendi");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tabelaMediDispon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMediDisponMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaMediDispon);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Médicos Disponíveis No Dia Corrente");

        painelatt3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                painelatt3MouseMoved(evt);
            }
        });
        painelatt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelatt3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelatt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelatt3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelatt3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelatt3MouseReleased(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconesNovos/icons8-Refresh-40.png"))); // NOI18N

        javax.swing.GroupLayout painelatt3Layout = new javax.swing.GroupLayout(painelatt3);
        painelatt3.setLayout(painelatt3Layout);
        painelatt3Layout.setHorizontalGroup(
            painelatt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        painelatt3Layout.setVerticalGroup(
            painelatt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelatt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelatt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        tabelaAgendadas.setBackground(new java.awt.Color(240, 240, 240));
        tabelaAgendadas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabelaAgendadas.getTableHeader().setReorderingAllowed(false);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaAgendadas, tabelaAgendadas);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fichaatend.paciente.nome}"));
        columnBinding.setColumnName("Paciente");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${medico.nome}"));
        columnBinding.setColumnName("Medico");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${situacao}"));
        columnBinding.setColumnName("Situacao");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tabelaAgendadas);
        if (tabelaAgendadas.getColumnModel().getColumnCount() > 0) {
            tabelaAgendadas.getColumnModel().getColumn(0).setResizable(false);
            tabelaAgendadas.getColumnModel().getColumn(2).setResizable(false);
        }

        painelatt2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                painelatt2MouseMoved(evt);
            }
        });
        painelatt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelatt2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelatt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelatt2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelatt2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelatt2MouseReleased(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconesNovos/icons8-Refresh-40.png"))); // NOI18N

        javax.swing.GroupLayout painelatt2Layout = new javax.swing.GroupLayout(painelatt2);
        painelatt2.setLayout(painelatt2Layout);
        painelatt2Layout.setHorizontalGroup(
            painelatt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
        );
        painelatt2Layout.setVerticalGroup(
            painelatt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
        );

        txtPesquisaData.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtPesquisaData.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPesquisaDataPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Pré-Consultas No Dia:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(txtPesquisaData, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelatt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesquisaData, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(painelatt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1553, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(199, 199, 199)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(200, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(215, 215, 215)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(216, Short.MAX_VALUE)))
        );

        areaDeTrabalho.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout areaDeTrabalhoLayout = new javax.swing.GroupLayout(areaDeTrabalho);
        areaDeTrabalho.setLayout(areaDeTrabalhoLayout);
        areaDeTrabalhoLayout.setHorizontalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        areaDeTrabalhoLayout.setVerticalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaDeTrabalhoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        medicamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/medicine.png"))); // NOI18N
        medicamentos.setText("Medicamentos");
        medicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicamentosActionPerformed(evt);
            }
        });

        jMenuItem6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jMenuItem6.setText("Opções");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        medicamentos.add(jMenuItem6);

        jMenuBar1.add(medicamentos);

        exames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/exames_icon.png"))); // NOI18N
        exames.setText("Exames");
        exames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examesActionPerformed(evt);
            }
        });

        jMenuItem10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jMenuItem10.setText("Opções");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        exames.add(jMenuItem10);

        jMenuBar1.add(exames);

        consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atendimento-pb.png"))); // NOI18N
        consultas.setText("Atendimentos");

        jMenuItem9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jMenuItem9.setText("Realizar Consulta");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        consultas.add(jMenuItem9);

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jMenuItem2.setText("Agendar Retorno");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        consultas.add(jMenuItem2);

        jMenuBar1.add(consultas);

        pesquisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search-2-xxl.png"))); // NOI18N
        pesquisas.setText("Pesquisas");

        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jMenuItem3.setText("Prontuários");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        pesquisas.add(jMenuItem3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jMenuItem5.setText("Pré-Consultas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        pesquisas.add(jMenuItem5);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem12.setText("Consultas");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        pesquisas.add(jMenuItem12);

        jMenuBar1.add(pesquisas);

        relat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconesNovos/icons8-Purchase Order-50.png"))); // NOI18N
        relat.setText("Relatorio de Consultas");
        relat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatActionPerformed(evt);
            }
        });

        jMenuItem11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jMenuItem11.setText("Pesquisar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        relat.add(jMenuItem11);

        jMenuBar1.add(relat);

        usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/doct.png"))); // NOI18N
        usuario.setText("     Usuário  ");

        jMenuItem7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jMenuItem7.setText("Editar Perfil");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        usuario.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jMenuItem8.setText("Sair");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        usuario.add(jMenuItem8);

        jMenuBar1.add(usuario);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconesNovos/icons8-Calendar-40.png"))); // NOI18N
        jMenuBar1.add(jMenu1);

        txtData.setText("data");
        jMenuBar1.add(txtData);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconesNovos/icons8-Stopwatch-40.png"))); // NOI18N
        jMenuBar1.add(jMenu2);

        txttime.setText("        horario");
        jMenuBar1.add(txttime);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaDeTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        PacienteProntuario manterPac;
        manterPac = new PacienteProntuario();

        areaDeTrabalho.add(manterPac);
        manterPac.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void medicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicamentosActionPerformed

    }//GEN-LAST:event_medicamentosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ManterMedicamento tela = new ManterMedicamento();
        areaDeTrabalho.add(tela);
        tela.setVisible(true);

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Inicio tela = new Inicio();

        tela.setVisible(true);
        ControleMedico.setLogado(null);
        ControleFuncionario.setLogado(null);
        this.dispose();

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TodasPreConsultas tela = new TodasPreConsultas();
        areaDeTrabalho.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        TelaConsulta tela = new TelaConsulta(medic);
        areaDeTrabalho.add(tela);
        tela.setVisible(true);
        try {
            tela.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(InicioMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        ManterExame tela = new ManterExame();
        areaDeTrabalho.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void examesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examesActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        TelaEditarPerfilMedico tela;
        tela = new TelaEditarPerfilMedico(null, true, medic);
        tela.setVisible(true);
        medic = tela.getSelecionado();
        usuario.setText(medic.getNome());

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaRetorno tela = new TelaRetorno();
        areaDeTrabalho.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        TodasConsultas tela = new TodasConsultas();
        areaDeTrabalho.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void tabelaMediDisponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMediDisponMouseClicked

    }//GEN-LAST:event_tabelaMediDisponMouseClicked

    private void painelatt3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelatt3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_painelatt3MouseMoved

    private void painelatt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelatt3MouseClicked
        listaMedicos.clear();

        listaMedicos.addAll(controleMed.medicosDisponiveisTudo());
        for (Medico m : listaMedicos) {
            int i = controlePrec.listaConsultasDataMed(new Date(), m).size();
            tabelaMediDispon.setValueAt(Integer.toString(m.getMaxatendi() - i), listaMedicos.indexOf(m), 2);

        }
    }//GEN-LAST:event_painelatt3MouseClicked

    private void painelatt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelatt3MouseEntered
        painelatt3.setBackground(Color.WHITE);
    }//GEN-LAST:event_painelatt3MouseEntered

    private void painelatt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelatt3MouseExited
        Color cinza = new Color(240, 240, 240);
        painelatt3.setBackground(cinza);
    }//GEN-LAST:event_painelatt3MouseExited

    private void painelatt3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelatt3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_painelatt3MousePressed

    private void painelatt3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelatt3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_painelatt3MouseReleased

    private void painelatt2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelatt2MouseMoved

    }//GEN-LAST:event_painelatt2MouseMoved

    private void painelatt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelatt2MouseClicked
        listaAgendadas.clear();
        listaAgendadas.addAll(controlePrec.pesquisaPrecData(txtPesquisaData.getDate()));
    }//GEN-LAST:event_painelatt2MouseClicked

    private void painelatt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelatt2MouseEntered
        painelatt2.setBackground(Color.WHITE);
    }//GEN-LAST:event_painelatt2MouseEntered

    private void painelatt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelatt2MouseExited
        Color cinza = new Color(240, 240, 240);
        painelatt2.setBackground(cinza);
    }//GEN-LAST:event_painelatt2MouseExited

    private void painelatt2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelatt2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_painelatt2MousePressed

    private void painelatt2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelatt2MouseReleased

    }//GEN-LAST:event_painelatt2MouseReleased

    private void txtPesquisaDataPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPesquisaDataPropertyChange

    }//GEN-LAST:event_txtPesquisaDataPropertyChange

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        TodasConsultasDataRelatorio tela = new TodasConsultasDataRelatorio();
        areaDeTrabalho.add(tela);
        tela.setVisible(true);


    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void relatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaDeTrabalho;
    private javax.swing.JMenu consultas;
    private javax.swing.JMenu exames;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.util.List<PreConsulta> listaAgendadas;
    private java.util.List<Medico> listaMedicos;
    private javax.swing.JMenu medicamentos;
    private javax.swing.JPanel painelatt2;
    private javax.swing.JPanel painelatt3;
    private javax.swing.JMenu pesquisas;
    private javax.swing.JMenu relat;
    private javax.swing.JTable tabelaAgendadas;
    private javax.swing.JTable tabelaMediDispon;
    private javax.swing.JMenu txtData;
    private com.toedter.calendar.JDateChooser txtPesquisaData;
    private javax.swing.JMenu txttime;
    private javax.swing.JMenu usuario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
